name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
   PUBLISHPATH: '.'
   Azure_Web_App: 'DemoWebAppSatya'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: dotnetpublish  
      run: dotnet publish --configuration Release -o '${{env.PUBLISHPATH}}/publish'
    - name: Azure WebApp Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: '${{env.Azure_Web_App}}/publish'
        publish-profile: '${{secrets.CONSTRING}}' 
        package: '${{env.PUBLISHPATH}}/publish'
